app:
  error-codes:
    user-inactive:
      code: 10001
      message: "Error: User is not active!"
    user-name-exist:
      code: 10002
      message: "Error: Username is already taken!"
    user-email-exist:
      code: 10003
      message: "Error: Email is already in use!"
    code-verify-failed:
      code: 10004
      message: "Error: Verification code verify failed!"
    doctor-exist:
      code: 10005
      message: "Error: Doctor already exist!"

